apiVersion: v1
kind: Secret
metadata:
  name: alternateid-dotfile-secret
data:
  .secret-file: "$BASE64CONNECTIONSTRING"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alternateid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alternateid
  template:
    metadata:
      labels:
        app: alternateid
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: alternateid-dotfile-secret
      containers:
      - name: alternateid
        image: $ACRNAME.azurecr.io/contoso-demo-alternate-id-service:$VERSION
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
        env:
        - name: DbConnectionString
          value: FilePath=/etc/secret-volume/.secret-file
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: AzureAd__Instance
          value: $AADINSTANCE
        - name: AzureAd__TenantId
          value: $AADTENANTID
        - name: AzureAd__Domain
          value: $AADDOMAIN
        - name: AzureAd__ClientId
          value: $AADCLIENTID
        - name: AzureAd__Audience
          value: $AADAUDIENCE         
---
apiVersion: v1
kind: Service
metadata:
  name: alternateid
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: alternateid