apiVersion: v1
kind: Secret
metadata:
  name: storagetrigger-dotfile-secret
data:
  .secret-conn-file: "$BASE64CONNECTIONSTRING"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
spec:
  secretTargetRef:
  - parameter: connection
    name: storagetrigger-dotfile-secret
    key: .secret-conn-file
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backendservice-queue-scaledobject  
spec:
  scaleTargetRef:
    name: backendservice
  replicas:
      min: 1
      max: 20
  triggers:
  - type: azure-queue
    metadata:
      queueName: $QUEUENAME
      accountName: $STORAGEACCOUNTNAME
      queueLength: "50"
    authenticationRef:
        name: azure-queue-auth