apiVersion: v1
kind: Secret
metadata:
  name: servicebustrigger-dotfile-secret
  labels:
    app: backendservice  
data:
  servicebus-connectionstring: $BASE64CONNECTIONSTRING
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  secretTargetRef:
  - parameter: connection
    name: servicebustrigger-dotfile-secret
    key: servicebus-connectionstring
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backendservice-queue-scaledobject
spec:
  scaleTargetRef:
    name: backendservice
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 1
  maxReplicaCount: 50    
  triggers:
  - type: azure-servicebus
    metadata:      
      queueName: $QUEUENAME
      messageCount: '50'
    authenticationRef:
        name: azure-servicebus-auth