apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - hosts:
        - $CUSTOMER_SERVICE_DOMAIN
      secretName: aks-csv-tls
    - hosts:
        - $MEMBER_PORTAL_DOMAIN
      secretName: aks-mem-tls
  rules:
    - host: $CUSTOMER_SERVICE_DOMAIN
      http:
        paths:
          - backend:
              service:
                name: customerservice
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix
    - host: $MEMBER_PORTAL_DOMAIN
      http:
        paths:
          - backend:
              service:
                name: memberportal
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix