apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memberservice
  template:
    metadata:
      labels:
        app: memberservice
    spec:
      volumes:
      - name: secrets-store-memberservice
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-podid"
      containers:
      - name: memberservice
        image: $ACRNAME.azurecr.io/contoso-demo-member-service:$VERSION
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        volumeMounts:
            - name: secrets-store-memberservice
              mountPath: "/mnt/secrets-store"
              readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80              
        env:
        - name: DbSource
          value: $DBSOURCE
        - name: DbName
          value: $DBNAME
        - name: DbUserId
          value: $DBUSERID
        - name: DbPassword
          valueFrom:
            secretKeyRef:
              name: contoso-customer-service-sql-password
              key: contoso-customer-service-sql-password
        - name: AlternateIdServiceUri
          value: http://alternateid.$NAMESPACE.svc.cluster.local          
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: AzureAd__Instance
          value: $AADINSTANCE
        - name: AzureAd__TenantId
          value: $AADTENANTID
        - name: AzureAd__Domain
          value: $AADDOMAIN
        - name: AzureAd__ClientId
          value: $AADCLIENTID
        - name: AzureAd__Audience
          value: $AADAUDIENCE              
---
apiVersion: v1
kind: Service
metadata:
  name: memberservice
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: memberservice
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: memberservice-scaledobject
    namespace: $NAMESPACE
    labels:
        deploymentName: memberservice    
spec:
    scaleTargetRef:
        name: memberservice
    pollingInterval: 30
    cooldownPeriod:  300
    minReplicaCount: 1
    maxReplicaCount: 100
    triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.$NAMESPACE.svc.cluster.local:9090
        metricName: http_requests_total
        threshold: '100'
        query: sum(rate(nginx_ingress_controller_requests{service='memberservice'}[1m]))
        namespace: $NAMESPACE    