apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memberportal
  template:
    metadata:
      labels:
        app: memberportal
    spec:
      volumes:
      - name: secrets-store-memberportal
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-podid"
      containers:
      - name: memberportal
        image: $ACRNAME.azurecr.io/contoso-demo-member-portal:$VERSION
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
            - name: secrets-store-memberportal
              mountPath: "/mnt/secrets-store"
              readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80              
        env:
        - name: AppInsightsInstrumentationKey
          value: $APPINSIGHTSKEY        
        - name: MemberPointsUrl
          value: http://pointsservice.$NAMESPACE.svc.cluster.local
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: AzureAdB2C__Instance
          value: $AADINSTANCEB2C
        - name: AzureAdB2C__Domain
          value: $AADDOMAINB2C
        - name: AzureAdB2C__ClientId
          value: $AADCLIENTIDB2C
        - name: AzureAdB2C__SignUpSignInPolicyId
          value: $AADPOLICYIDB2C
        - name: AzureAdB2C__SignedOutCallbackPath
          value: $AADSIGNOUTCALLBACKPATHB2C             
        - name: AzureAd__Instance
          value: $AADINSTANCE
        - name: AzureAd__TenantId
          value: $AADTENANTID
        - name: AzureAd__ClientId
          value: $AADCLIENTID
        - name: AzureAd__ClientSecret
          value: $AADCLIENTSECRET
        - name: AzureAd__Scopes
          value: $AADSCOPES         
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: memberportal
spec:  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: memberportal